import "./globals.css";
import { Roboto } from "next/font/google";
import { cn } from "@/lib/Utils";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["300", "400", "500", "700"], // Include multiple weights
  subsets: ["latin"], // Specify character subset
  display: "swap", // Optimize font loading
  variable: "--font-roboto", // Create a CSS variable for Tailwind
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.variable}>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          roboto.className // Apply Roboto as the default font
        )}
      >
        {children}
      </body>
    </html>
  );
}
